#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -std=c++0x -Wall
RESINC = 
LIBDIR = 
LIB = libs/libjson_linux-gcc-4.6_libmt.so libs/libWordsSegment.so
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)#-l/libs/libjson_linux-gcc-4.6_libmt.so -l/libs/libWordsSegment.so
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/spam_msg

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/spam_msg

OBJ_DEBUG = $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/DataGenerator.o $(OBJDIR_DEBUG)/DataLearner.o $(OBJDIR_DEBUG)/DataParser.o $(OBJDIR_DEBUG)/DataPredictor.o $(OBJDIR_DEBUG)/DictionaryMan.o $(OBJDIR_DEBUG)/FeatureMan.o $(OBJDIR_DEBUG)/AddressMan.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/DataGenerator.o $(OBJDIR_RELEASE)/DataLearner.o $(OBJDIR_RELEASE)/DataParser.o $(OBJDIR_RELEASE)/DataPredictor.o $(OBJDIR_RELEASE)/DictionaryMan.o $(OBJDIR_RELEASE)/FeatureMan.o $(OBJDIR_RELEASE)/AddressMan.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/DataGenerator.o: DataGenerator.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c DataGenerator.cpp -o $(OBJDIR_DEBUG)/DataGenerator.o

$(OBJDIR_DEBUG)/DataLearner.o: DataLearner.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c DataLearner.cpp -o $(OBJDIR_DEBUG)/DataLearner.o

$(OBJDIR_DEBUG)/DataParser.o: DataParser.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c DataParser.cpp -o $(OBJDIR_DEBUG)/DataParser.o

$(OBJDIR_DEBUG)/DataPredictor.o: DataPredictor.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c DataPredictor.cpp -o $(OBJDIR_DEBUG)/DataPredictor.o

$(OBJDIR_DEBUG)/DictionaryMan.o: DictionaryMan.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c DictionaryMan.cpp -o $(OBJDIR_DEBUG)/DictionaryMan.o

$(OBJDIR_DEBUG)/FeatureMan.o: FeatureMan.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c FeatureMan.cpp -o $(OBJDIR_DEBUG)/FeatureMan.o

$(OBJDIR_DEBUG)/AddressMan.o: AddressMan.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c AddressMan.cpp -o $(OBJDIR_DEBUG)/AddressMan.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/DataGenerator.o: DataGenerator.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c DataGenerator.cpp -o $(OBJDIR_RELEASE)/DataGenerator.o

$(OBJDIR_RELEASE)/DataLearner.o: DataLearner.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c DataLearner.cpp -o $(OBJDIR_RELEASE)/DataLearner.o

$(OBJDIR_RELEASE)/DataParser.o: DataParser.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c DataParser.cpp -o $(OBJDIR_RELEASE)/DataParser.o

$(OBJDIR_RELEASE)/DataPredictor.o: DataPredictor.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c DataPredictor.cpp -o $(OBJDIR_RELEASE)/DataPredictor.o

$(OBJDIR_RELEASE)/DictionaryMan.o: DictionaryMan.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c DictionaryMan.cpp -o $(OBJDIR_RELEASE)/DictionaryMan.o

$(OBJDIR_RELEASE)/FeatureMan.o: FeatureMan.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c FeatureMan.cpp -o $(OBJDIR_RELEASE)/FeatureMan.o

$(OBJDIR_RELEASE)/AddressMan.o: AddressMan.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c AddressMan.cpp -o $(OBJDIR_RELEASE)/AddressMan.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

